version: '2.2'
services:
  dynamo:
    networks:
      - default
    image: amazon/dynamodb-local
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - './data:/home/dynamodblocal/data'
    # entrypoint:
    #   - "./data/init-dynamodb.sh"